include:
  - project: 'frontend/ci-templates'
    file: 'common/rules.yml'
    ref: master
  - project: 'frontend/ci-templates'
    file: 'common/registries.yml'
    ref: master

default:
  image: docker-register-registry-vpc.cn-shanghai.cr.aliyuncs.com/well-known/node:16
  before_script:
    - npm config set registry https://registry.npmmirror.com
    - npm config set httpProxy http://10.18.252.1:6152
    - npm config set httpsProxy http://10.18.252.1:6152
    - npm instal -g pnpm @microsoft/rush
    - !reference [.registry_echo_gitlab_auth, script]
    - rush update
    - echo "{\"accessKeyId\":\"${G_OSS_KEY}\",\"accessKeySecret\":\"${G_OSS_SECRET}\"}" > .alioss.json
  tags:
    - wx-docker

# job_publish:
#   rules:
#    - !reference [.rule_if_pr, rules]

# job_deploy_storybook:
#   rules:
#     - !reference [.rule_if_pr, rules]
#   script:
#     - rush build:storybook
#     - rush deploy:storybook

job_test:
  rules:
    - !reference [.rule_if_pr, rules]
  script:
    - rush test:unit

# 手动触发
job_update_icon:
  variables:
    ICONPARK_URL:
      value: ''
  rules:
    - if: '$ICONPARK_URL'
      when: always
  script:
    - git config user.email "${GITLAB_USER_NAME}"
    - git config user.name "${GITLAB_USER_EMAIL}"
    - TIME=$(date +%Y%m%d%H%M)
    - BRANCH_NAME=feat-update-icons-$TIME
    - git checkout -b $BRANCH_NAME
    - $ICONPARK_URL == $(cat ./apps/du-icon/icon-url) && exit 0
    - echo $ICONPARK_URL > ./apps/du-icon/icon-url
    - cd apps/du-icon
    - pnpm run genicon
    - cd -
    - git add .
    - 'git commit -m "feat(du-icon): update icons ${TIME}"'
    - git push https://ci:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git $BRANCH_NAME -o merge_request.create -o merge_request.target=master
